version: 1
# deployment:
#   production: # just a label; label names are completely up to you
#     branch: master
#     commands:
#       - ../build/deploy.sh
  # staging:
  #   branch: staging
  #   commands:
  #     - ./deploy-to-staging.sh

jobs:
  build:
    docker:
      - image: circleci/php:5
    general:
      build_dir: data/public
    steps:
      - checkout
        # - post:
        #   - run: cp .circleci/blah.foo.yml config/foo.yml
      - run: echo "build"
      - run: sudo pear install MDB2-2.5.0b5
      - run: sudo pear install DB-1.9.2
      - run: sudo pear install DB_DataObject-1.11.5
      - run: sudo pear install --nodeps MDB2_Driver_mysqli-1.4.1
      - run: sudo pear install Mail-1.4.1
      - run: sudo pear install Mail_mime-1.10.2
  deployment:
    docker:
      - image: circleci/php:5
    steps:
      - checkout
      - run: echo "deployment changed..."
      - run: tar -zcvf test.tar.gz src/
      - run: scp test.tar.gz sokonokado@52.66.73.199:/home/sokonokado/
      # - run: ./build/deploy.sh
    # branch: master
    # commands:
    #   - ../build/deploy.sh
#
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
