version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "build"
      # - run: <command>
  test1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "test1"
      # - run: <command>
  test2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "test2"
      # - run: <command>
  hold:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "hold"
      # - run: <command>
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      # - run: <command>
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - hold:
          type: approval
          requires:
           - test2
      - deploy:
          requires:
            - hold
